package bitshyd.dbmsproject.web.controller;

import java.io.IOException;
import java.util.Random;

import bitshyd.dbmsproject.web.dao.UserDao;
import bitshyd.dbmsproject.web.model.User;
import bitshyd.dbmsproject.web.services.Helper;
import bitshyd.dbmsproject.web.services.SendMail;
import jakarta.servlet.RequestDispatcher;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

/**
 * Servlet implementation class LoginController
 */
public class LoginController extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		User objuser = new User();
		forwardRequest(objuser, "Login.jsp", request, response);
	}
	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		
		String actionType= request.getParameter("actionType"); 
		String strUserName = request.getParameter("username");
		String strEncryptedPassword = Helper.encrypt(request.getParameter("passwd"));
		UserDao objUserDao = new UserDao();
		User objuser=objUserDao.getCustomer(strUserName);
		if (actionType.equalsIgnoreCase("fp")) {
			if (objuser == null || objuser.getUserId()==0) {
				objuser.setErrorMsg(" Given username is not found!!");
			}
			else {
				sendForgotPasswordMail(objuser);
				objuser.setErrorMsg(" An email is sent to your registered emailid to reset password ");
			}
		}
		else if (objuser == null || objuser.getUserId()==0 || !objuser.getUserPassword().equals(strEncryptedPassword)) {
			objuser.setErrorMsg(" Invalid credentails ");
		}
		else if (objuser.getUserStatusId() == 2) {
			objuser.setErrorMsg("Your Account is Blocked!!");
		}
		else if (objuser.getUserStatusId() == 1) {
			HttpSession session = request.getSession();
			session.setAttribute("UserID", objuser.getUserId());
			session.setAttribute("Username", objuser.getUsername());
			session.setAttribute("Name", objuser.getFirstName());
			session.setAttribute("UserTypeId", objuser.getUserTypeId());
			session.setAttribute("UserRole", objuser.getUserType());

			response.sendRedirect("Dashboard"); 
			return;
		} 
		
		forwardRequest(objuser, "Login.jsp", request, response);
		return;
		
	}
	
	private void sendForgotPasswordMail(User user) {
		int randomKey= new  Random().nextInt();
		if (randomKey < 0) {
			randomKey = -1 * randomKey;
		}
		//System.out.print("Random Key Generated is " + randomKey);
		new UserDao().saveResetPasswordKeyDetails(user.getUserId(), String.valueOf(randomKey));
		String mailSubject = "Reset Password of Work Space Booking Solutions";
		String mailContent = "Link provided below is generated by Work Space Booking Solutions on your request to reset the login password.\n"
				+ "http://localhost:8080/WorkSpaceBookingSolutions/PasswordReset?fp=" + randomKey;
		SendMail.send(user.getEmailID(), mailSubject, mailContent);
	}
	
	private void forwardRequest(User model, String pagename, HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
	{
		request.setAttribute("model", model);
		RequestDispatcher rd = request.getRequestDispatcher(pagename);
		rd.forward(request, response);	
	}
	
}
